package consts

var (
	DEVELOPMENT             = "DEVELOPMENT"
	LOG_JSON_LOGGING        = "LOG_JSON_LOGGING"
	LOG_LEVEL               = "LOG_LEVEL"
	LOG_COLORIZE            = "LOG_COLORIZE"
	LOG_ADD_CALLER          = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRANCE = "LOG_DISABLE_STACKTRANCE"
	LOG_UNESCAPE_MULTILINE  = "LOG_UNESCAPE_MULTILINE"
	VITISTACKCRDNAME        = "VITISTACKCRDNAME"
	CONFIGMAPNAME           = "CONFIGMAPNAME"
	NAMESPACE               = "NAMESPACE"
)
