package consts

var (
	VITISTACKCRDNAME = "VITISTACKCRDNAME"
	CONFIGMAPNAME    = "CONFIGMAPNAME"
	NAMESPACE        = "NAMESPACE"
	DEVELOPMENT      = "DEVELOPMENT"
	REGION           = "REGION"
	LOCATION         = "LOCATION"
)
