package consts

var (
	DATACENTERCRDNAME = "DATACENTERCRDNAME"
	CONFIGMAPNAME     = "CONFIGMAPNAME"
	NAMESPACE         = "NAMESPACE"
	DEVELOPMENT       = "DEVELOPMENT"
	REGION            = "REGION"
	LOCATION          = "LOCATION"
)
